spring:
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.8.151:3306/zr
    username: root
    password: 657431zhurui
  #redis
  redis:
    host: zryyds.xyz
    port: 6379
  #mail
  mail:
    username: 862739771@qq.com
    password: fjyqxtaczatjbcfi
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #关闭缓存
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 80


#zr为使用路径
#Linux
zr:
  loadlocation: '/home/data'
  videopath: 'file:/home/data/video/'
  rootpath: 'file:/home/data/root/'

#windows
zr？:
  loadlocation: 'G:/data'
  videopath: 'file:/G:/data/video/'
  rootpath: 'file:/G:/data/root/'

